### ISSUE TITLE
DAO Concept

### ISSUE THREAD

**Issue by BenGOsborn** [Terragonn/Wabbit-Protocol#13]
# Wabbit DAO

- Governance token used for voting
    - Governance tokens may be earned from staking in the protocol - only a fixed amount however
    - Governance tokens entitle the DAO to passive income in the form of dividends earned by the protocol
- Use the DAO's treasury to payout "employees" who operate various functions in the protocol

## Todos
- [x] Dividends and task incentives
- [x] Token supply and yield farming rewards
- [x] Owner funding and excess funding for the DAO

**Comment by BenGOsborn** [comment]
Pay out dividends to voters through the timelock without requiring approval every given timeframe.

**Comment by BenGOsborn** [comment]
Fix the token yields to be dependent on the amount of the asset staked AND have their own rate.

**Comment by BenGOsborn** [comment]
> Fix the token yields to be dependent on the amount of the asset staked AND have their own rate.

Fixed in d552863066ec40c4bc1e94b19dd3cdc160d87ad5

**Comment by BenGOsborn** [comment]
> Pay out dividends to voters through the timelock without requiring approval every given timeframe.

Fixed in a85c51be2230afb6a8aaae84c88e1812c0fd59af
